-- Run as SYS (per image behavior)
ALTER SESSION SET CONTAINER=FREEPDB1;

-- App user for SCN-based cache tests
CREATE USER SOMEUSER IDENTIFIED BY cache
  DEFAULT TABLESPACE USERS
  QUOTA UNLIMITED ON USERS;

GRANT CREATE SESSION TO SOMEUSER;
GRANT CREATE TABLE, CREATE SEQUENCE, CREATE PROCEDURE, CREATE VIEW, CREATE TRIGGER TO SOMEUSER;

-- SELECT current_scn FROM v$database)
GRANT SELECT ON V_$DATABASE TO SOMEUSER;
