import argparse
import os
from pathlib import Path

import polars as pl


def _with_prefix(prefix: str, base_name: str) -> str:
    return f"{prefix}{base_name}"


def _generate_df_prefixed(
        *,
        n_rows: int,
        n_cols: int,
        seed: int | None,
        prefix: str,
        float_scale: float,
        n_int_cols: int,
        n_str_cols: int,
) -> pl.DataFrame:
    """
    Create the same *shape & column naming convention* as your CSV generator,
    but directly as a Polars DataFrame.

    Column naming:
      {prefix}COL_INT64_1..n_int_cols
      {prefix}COL_F64_1..n_float_cols
      {prefix}COL_STR_1..n_str_cols

    Data:
      - int cols: int64 in a moderately-sized keyspace (duplicates => joins do work)
      - float cols: uniform[0,1) * float_scale
      - str cols: generated by casting random int32 to Utf8 (fast, no Python loops)
    """
    import numpy as np  # local import

    if n_cols < (n_int_cols + n_str_cols):
        raise ValueError("n_cols must be >= n_int_cols + n_str_cols")

    n_float_cols = n_cols - n_int_cols - n_str_cols

    rng = np.random.default_rng(seed)

    # A keyspace that grows with n_rows so join cost scales sensibly.
    key_mod = max(1, n_rows * 2)

    cols: dict[str, object] = {}

    # int64 columns
    for j in range(1, n_int_cols + 1):
        name = f"{prefix}COL_INT64_{j}"
        cols[name] = rng.integers(0, key_mod, size=n_rows, dtype=np.int64)

    # float64 columns
    for j in range(1, n_float_cols + 1):
        name = f"{prefix}COL_F64_{j}"
        cols[name] = (rng.random(n_rows, dtype=np.float64) * float_scale)

    # string columns (fast: ints -> cast to Utf8)
    for j in range(1, n_str_cols + 1):
        name = f"{prefix}COL_STR_{j}"
        s = pl.Series(
            name,
            rng.integers(0, 10_000_000, size=n_rows, dtype=np.int32),
        ).cast(pl.Utf8)
        cols[name] = s

    return pl.DataFrame(cols)


def ensure_one_parquet(
        *,
        out_dir: Path,
        base_name: str,
        prefix: str,
        n_rows: int,
        n_cols: int,
        seed: int | None,
        float_scale: float,
        n_int_cols: int,
        n_str_cols: int,
) -> Path:
    out_dir.mkdir(parents=True, exist_ok=True)

    out_name = _with_prefix(prefix, base_name)
    out_path = out_dir / out_name

    df = _generate_df_prefixed(
        n_rows=int(n_rows),
        n_cols=int(n_cols),
        seed=seed,
        prefix=prefix,
        float_scale=float(float_scale),
        n_int_cols=int(n_int_cols),
        n_str_cols=int(n_str_cols),
    )
    part_path = out_path.with_name(f"{out_path.name}.part")
    df.write_parquet(str(part_path), compression="uncompressed", statistics="full")
    os.replace(part_path, out_path)
    return out_path


def underscore_int(n: int) -> str:
    return f"{n:,}".replace(",", "_")


def main(args) -> int:
    data_dir = Path(args.data_dir)
    seed = None if args.seed is None else int(args.seed)
    for N in range(int(args.n_min), int(args.n_max) + 1):
        n_rows = 1 << N
        base_name = f"TEST_{n_rows}.parquet"

        print(f"\n=== N={N} rows={n_rows} cols={args.cols} ===")

        left_par = ensure_one_parquet(
            out_dir=data_dir,
            base_name=base_name,
            prefix="A_",
            n_rows=n_rows,
            n_cols=int(args.cols),
            seed=seed,
            float_scale=float(args.float_scale),
            n_int_cols=int(args.n_int_cols),
            n_str_cols=int(args.n_str_cols),
        )

        right_par = ensure_one_parquet(
            out_dir=data_dir,
            base_name=base_name,
            prefix="B_",
            n_rows=n_rows,
            n_cols=int(args.cols),
            seed=seed,
            float_scale=float(args.float_scale),
            n_int_cols=int(args.n_int_cols),
            n_str_cols=int(args.n_str_cols),
        )

    return 0


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--n-min", type=int, default=20)
    ap.add_argument("--n-max", type=int, default=20)
    ap.add_argument("--cols", type=int, default=20)
    ap.add_argument("--data-dir", default="../../parquet")
    ap.add_argument("--seed", type=int, default=None)
    ap.add_argument("--float-scale", type=float, default=5.0)
    ap.add_argument("--n-int-cols", type=int, default=4)
    ap.add_argument("--n-str-cols", type=int, default=8)
    args = ap.parse_args()
    raise SystemExit(main(args))
